const INC = "INC";
const DEC = "DEC";
const USER_FETCH_IN_PROGRESS = "USER_FETCH_IN_PROGRESS";
const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
const USER_FETCH_FAILED = "USER_FETCH_FAILED";

export { INC, DEC, USER_FETCH_IN_PROGRESS, USER_FETCH_SUCCESS, USER_FETCH_FAILED };