const INC = "INC";
const DEC = "DEC";
const USER_FETCH_IN_PROGRESS = "USER_FETCH_IN_PROGRESS";
const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
const USER_FETCH_FAILED = "USER_FETCH_FAILED";
const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
const USER_ADD_REQUEST = "USER_ADD_REQUEST";
const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
const USER_ADD_FAILED = "USER_ADD_FAILED";

export {
    INC, DEC, USER_FETCH_REQUEST,
    USER_FETCH_IN_PROGRESS,
    USER_FETCH_SUCCESS, USER_FETCH_FAILED,
    USER_ADD_REQUEST,
    USER_ADD_SUCCESS,
    USER_ADD_FAILED
};